image: elixir:1.6

variables:
  MIX_ENV: "test"

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test

test:
  script:
    - mix compile --warnings-as-errors
    - mix test
